#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/CameraPlugIns/"

cp "/tmp/SVBony_X2/cameralist SVBony.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SVBonyCamSelect.ui"
cp "/tmp/SVBony_X2/SVBonyCamSelect.ui" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SVBonyCamera.ui"
cp "/tmp/SVBony_X2/SVBonyCamera.ui" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SVBony.png"
cp "/tmp/SVBony_X2/SVBony.png" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/libSVBony.dylib"
cp "/tmp/SVBony_X2/libSVBony.dylib" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/cameralist SVBony.txt"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SVBonyCamSelect.ui"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SVBonyCamera.ui"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SVBony.png"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/libSVBony.dylib"
fi

rm -rf /tmp/SVBony_X2

